### PR TITLE
feat(projects/clearpool): Implement `zkEVM` `tvl` and `borrowed`.

### PR DESCRIPTION
**Pull request by power-f-GOD**

### CODE REVIEW

**Comment by llamatester** [comment]
The adapter at projects/clearpool exports TVL: 
        
 
 
    ethereum-staking          5.42 M
    ethereum-borrowed         19.82 M
    ethereum                  4.27 M
    polygon                   79.11 k
    polygon-borrowed          0.016976959999999996
    polygon_zkevm             23.38 k
    polygon_zkevm-borrowed    65.18 k
    staking                   5.42 M
    borrowed                  19.89 M
    
    total                    4.37 M

**Comment by georgeciubotaru** [comment]
@power-f-GOD The failed test cases not related to our changes?

**Review by georgeciubotaru — APPROVED** [review]

**Comment by power-f-GOD** [comment]
> @power-f-GOD The failed test cases not related to our changes?

Yeah. Seemed someone pushed an erring code.

**Comment by power-f-GOD** [comment]
Upstream PR for `zkEVM` implementation: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7008

**Pull request merged**
