### PR TITLE
Updating the endpoint to get tvl pools on polygon 

### PR DESCRIPTION
**Pull request by korzhanov**
**Template**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

---
##### Name (to be shown on DefiLlama): Clearpool
WE ARE UPDATING EXISTING ADAPTER

### CODE REVIEW

**Comment by korzhanov** [comment]
https://github.com/clearpool-finance/clearpool.finance/issues/161

https://github.com/clearpool-finance/clearpool.finance/pull/162

**Comment by irondsd** [comment]
This code manually parses blockchain events. It's pretty bad. We have better tools for it, lens and subgraph. Can we use them here?

**Comment by korzhanov** [comment]
> This code manually parses blockchain events. It's pretty bad. We have better tools for it, lens and subgraph. Can we use them here?

This adapter code was written before the introduction of subgraph.
Therefore, if it is fast, it is quite possible to do

**Comment by irondsd** [comment]
let's schedule a refactoring of this code for the future

**Comment by irondsd** [comment]
Not now though. We should get rid of backend as quickly as possible. If it works, it works.

**Comment by VarinderSS1113** [comment]
@drugz same here please, do not pull tasks into in-review, the reviewer should be the one pulling it into review column. Remember we do not dump tasks on teammates, we allow them to pull, and if they are not available, we look for someone else's help! Thanks
Please also assign people that are blocking or that you require input from.

**Comment by irondsd** [comment]
I already reviewed it. It looks fine. If it works, we can merge it.

**Comment by VarinderSS1113** [comment]
Thank you @irondsd 
If you have review the code and tested that it works, then please do what needs to be done to deliver this to done. 
Feel free to communicate with @drugz to check if all tests were completed, if yes, let's proceed please. Thank you

@drugz please take ownership here and push this task to completion as well, we are all here to help! Thanks

**Comment by irondsd** [comment]
I can't be sure that it works, because I honestly have no idea how to test this. Oleg, have you tested it?

**Comment by irondsd** [comment]
If so, let's just merge it

**Comment by korzhanov** [comment]
> I can't be sure that it works, because I honestly have no idea how to test this. Oleg, have you tested it?

Sure. I left comment in the head of adapter

```
npm i -f
node test.js projects/clearpool/index.js
```
additionally DefiLlama will be tested in additional upstream PR

**Review by georgeciubotaru — APPROVED** [review]

**Review by irondsd — APPROVED** [review]

**Comment by korzhanov** [comment]
Waiting for review
https://github.com/DefiLlama/DefiLlama-Adapters/pull/4809

**Pull request merged**
