### PR TITLE
Add Clearpool staking TVL to DefiLllama adapter

### PR DESCRIPTION
**Pull request by zolotokrylin**
**NOTE**

1. The protocol is usually listed within 24 hours of merging the PR
2. Please fill the form below  **only if the PR is for listing a new protocol** else it can be ignored/replaced with reason/details about the PR
3. **For updating listing info** It is a different repo, you can find your listing in this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data2.ts, you can  edit it there and put up a PR
4. Do not edit/push `package-lock.json` file as part of your changes, we use lockfileVersion 2, and most use v1 and using that messes up our CI
5. No need to go to our discord and announce that you've created a PR, we monitor all PRs and will review it asap

------------

WE ARE UPDATING EXISTING ADAPTER

### CODE REVIEW

**Comment by llamatester** [comment]
Error while running adapter at projects/clearpool: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/clearpool: 
        
 
  
    
    
    Error: 
        Found export keys that were not part of specification: staked
    
        List of valid keys: 
    				
    				tvl
    				staking
    				methodology
    				pool2
    				misrepresentedTokens
    				fetch
    				timetravel
    				borrowed
    				start
    				masterchef
    				doublecounted
    				treasury
    				hallmarks
    				incentivized
    				offers
    				deadFrom
    				broken
    				ownTokens
    				vesting

**Comment by llamatester** [comment]
Error while running adapter at projects/clearpool: 
        
 
  
    
    
    TypeError: Cannot read properties of undefined (reading 'tvl')
    Truncated error stack:
    
        at ethereumStaked (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/projects/clearpool/index.js:71:18)
        at async getTvl (/home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:60:25)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:167:9
        at async Promise.all (index 2)
        at async Promise.all (index 1)
        at async /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:212:3

**Comment by llamatester** [comment]
The adapter at projects/clearpool exports TVL: 
        
 
 
    ethereum-staking          0
    polygon-borrowed          38.60 M
    polygon                   6.32 M
    ethereum                  6.12 M
    ethereum-borrowed         41.69 M
    staking                   0
    borrowed                  80.29 M
    
    total                    12.43 M

**Comment by korzhanov** [comment]
@llamatester  Can we use a number for the staking value or do we need to provide an object?

**Comment by llamatester** [comment]
The adapter at projects/clearpool exports TVL: 
        
 
 
    ethereum-staking          0
    polygon                   6.32 M
    polygon-borrowed          38.60 M
    ethereum-borrowed         41.69 M
    ethereum                  6.12 M
    staking                   0
    borrowed                  80.30 M
    
    total                    12.43 M

**Comment by llamatester** [comment]
The adapter at projects/clearpool exports TVL: 
        
 
 
    ethereum-staking          0
    polygon                   6.32 M
    polygon-borrowed          38.60 M
    ethereum-borrowed         41.69 M
    ethereum                  6.12 M
    staking                   0
    borrowed                  80.30 M
    
    total                    12.43 M

**Comment by llamatester** [comment]
Error while running adapter at projects/clearpool: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/clearpool: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/clearpool: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
The adapter at projects/clearpool exports TVL: 
        
 
 
    polygon-borrowed          38.55 M
    polygon                   6.31 M
    ethereum-borrowed         41.63 M
    ethereum                  6.11 M
    borrowed                  80.18 M
    
    total                    12.41 M

**Comment by llamatester** [comment]
Error while running adapter at projects/clearpool: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/clearpool: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Comment by llamatester** [comment]
Error while running adapter at projects/clearpool: 
        
 
  
    
    
    Error: Protocol doesn't have total tvl, make sure to export a tvl key either on the main object or in one of the chains
    Truncated error stack:
    
        at /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/test.js:224:11

**Pull request merged**
